### ISSUE TITLE
Details about these TADF molecules

### ISSUE THREAD

**Issue by JerryShuaiWANG** [Dingyun-Huang/chemdataextractorTADF#1]
Dear Dr. Huang,

It is such a great and valuable work.

I am a bit confused about if all the TADF molecules in the database are pure organic (i.e., no metal atoms). Also, are all the molecules represented in SMILES format?

Many thanks,
Jerry

**Comment by Dingyun-Huang** [comment]
Hi Jerry,

Sorry for the late reply. Yes, the database intended to present organic molecular TADF materials only, but there is a small fraction of organo-metallic complexes. Around 5k records out of the 25k records has SMILES strings. Check out [Figshare](https://figshare.com/articles/dataset/A_Database_of_Thermally_Activated_Delayed_Fluorescent_Molecules_Auto-generated_from_Scientific_Literature_with_ChemDataExtractor/24004182) subsidiary database for all records with SMILES. The extraction processes are discussed in details here [Sci. Data. paper](https://www.nature.com/articles/s41597-023-02897-3).

**Comment by JerryShuaiWANG** [comment]
Hi Dr. Huang,

Thanks for the reply. I have checked the Figshare and can see the samples with SMILES representations. However, cannot find the organo-metallic complexes (sorry for this).

May I kindly know the details about these organo-metallic complexes? For instance, 1) the number 2) the metal elements involved 3) how do the complexes represent?

Many thanks for your time and kindness!

Best,
Jerry

**Comment by Dingyun-Huang** [comment]
Hi Jerry,

The data extraction pipeline is designed to collect molecular TADF materials only. There was no special treatment for organo-metallic complexes, as they have different naming conventions.

There are some tricks that you may want to try.
* Search for compounds with '[' or ']' in their names, as the ligand names are often contained in[].
* Search for compounds with common metal ions like Cu2+ etc.

You are welcome to gather research papers of organo-metallic TADF materials and re-run the data extraction pipeline, which would be a full solution.

Hope this helps,
Dingyun

**Comment by JerryShuaiWANG** [comment]
> Hi Jerry,
> 
> The data extraction pipeline is designed to collect molecular TADF materials only. There was no special treatment for organo-metallic complexes, as they have different naming conventions.
> 
> There are some tricks that you may want to try.
> 
> * Search for compounds with '[' or ']' in their names, as the ligand names are often contained in[].
> * Search for compounds with common metal ions like Cu2+ etc.
> 
> You are welcome to gather research papers of organo-metallic TADF materials and re-run the data extraction pipeline, which would be a full solution.
> 
> Hope this helps, Dingyun

Hi Dr. Huang,

Thanks for the reply and suggestions.

Have a nice day!
 
Best,
Jerry
